### ISSUE TITLE
Add question to students on each notebook: How long did this take?

### ISSUE THREAD

**Issue by veitveit** [oercompbiomed/CBM101#3]
Add it as default, i.e. to notebook template

What would be the format? Hours? 

Anything that can be easily extracted.

**Comment by veitveit** [comment]
A _First question_ has been added to the template: https://github.com/oercompbiomed/CBM101/blob/master/Template-Topic/template_subtopic1/template.ipynb

Would that work? Otherwise I will close this issue

**Comment by karinSDU** [comment]
I will suggest that we at the top of the notebook make them aware that we would like them to answer the questions at the end of the notebook - and then add the question at the very end of the notebook. Otherwise I think they will forget to answer.

**Comment by veitveit** [comment]
Good point and done.
