### ISSUE TITLE
I have uploaded a notebook in very basic network analysis using the template - please check it out

### ISSUE THREAD

**Issue by karinSDU** [oercompbiomed/CBM101#6]
- I did not manage to make the last part of the exercise as I still need to learn how to color nodes based on attibutes.

**Comment by veitveit** [comment]
https://github.com/oercompbiomed/CBM101/blob/master/C_Network-Analysis/Basic-network-analysis/Network_graphs_1_students.ipynb

Looks good!

**Comment by veitveit** [comment]
See #7
